name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # تشغيل الـ workflow كل يوم
  workflow_dispatch:  # إمكانية تشغيله يدويًا

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: abdalahsamh
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Push the SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

